# Generated by Django 5.0.7 on 2024-07-22 14:51

import datetime
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EventFormat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('format', models.JSONField(default=['!event.cash'])),
            ],
        ),
        migrations.CreateModel(
            name='Prompt',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
                ('format', models.JSONField(default=['This is metadata for you to remember', '!config.context', '\nThese are the last', '!config.past_events_size', 'events that have taken place:\n', '!past_events', '\n\nBased on these events, generate a ', '!reaction.name', 'message to be said to the user. Phrase the message in a ', '!reaction.name', ' manner and ensure it aligns with your objective and personality. Limit it to a sentence with at most 20 words.'])),
            ],
        ),
        migrations.CreateModel(
            name='Reaction',
            fields=[
                ('name', models.CharField(max_length=26, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('name', models.CharField(max_length=26, primary_key=True, serialize=False, unique=True)),
                ('objective', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('cash', models.FloatField(default=0)),
                ('is_vampire', models.BooleanField(default=False)),
                ('is_survivor', models.BooleanField(default=False)),
                ('inventory', models.JSONField(blank=True, null=True)),
                ('trigger_time', models.DateTimeField(default=datetime.datetime.now)),
                ('trigger', models.CharField(blank=True, max_length=50, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('team', models.ManyToManyField(blank=True, related_name='team', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('prompt', models.TextField()),
                ('content', models.TextField()),
                ('context', models.TextField()),
                ('sent_time', models.DateTimeField(default=datetime.datetime.now)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('reaction', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='llm.reaction')),
                ('role', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='llm.role')),
            ],
        ),
        migrations.CreateModel(
            name='Config',
            fields=[
                ('context', models.JSONField(blank=True, null=True)),
                ('past_events_size', models.IntegerField(default=5)),
                ('include_prev_conv', models.BooleanField(default=True)),
                ('id', models.UUIDField(default='88cb3fc06b71449b9b3a029904c8820d', editable=False, primary_key=True, serialize=False)),
                ('event_fromat', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='llm.eventformat')),
                ('prompt', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='llm.prompt')),
                ('default_reaction', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='llm.reaction')),
                ('default_role', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='llm.role')),
            ],
        ),
    ]
