# Generated by Django 5.0.7 on 2024-07-16 16:11

import datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('llm', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='coaches',
        ),
        migrations.RemoveField(
            model_name='event',
            name='members',
        ),
        migrations.AddField(
            model_name='event',
            name='cash',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='event',
            name='inventory',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='isSurvivor',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='event',
            name='isVampire',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='event',
            name='trigger',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='triggerTime',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.RemoveField(
            model_name='event',
            name='team',
        ),
        migrations.AddField(
            model_name='event',
            name='team',
            field=models.ManyToManyField(blank=True, null=True, related_name='team', to=settings.AUTH_USER_MODEL),
        ),
    ]
