# Generated by Django 5.0.7 on 2024-07-22 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('llm', '0002_remove_config_event_fromat'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='wave',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='event',
            name='winner',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
