# Generated by Django 5.0.7 on 2024-07-16 18:13

import datetime
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('llm', '0004_alter_event_trigger'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('prompt', models.TextField()),
                ('content', models.TextField()),
                ('context', models.TextField()),
                ('reaction', models.CharField(choices=[('funny', 'funny')], default='funny', max_length=5)),
                ('sentTime', models.DateTimeField(default=datetime.datetime.now)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
